# Generated by Django 5.1.5 on 2025-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiederModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام لیدر')),
            ],
            options={
                'verbose_name': 'create lider',
                'verbose_name_plural': 'create liders',
            },
        ),
    ]
